#+ summary: Returns a list of suggested terms
#+ endpoint: http://data.dive.beeldengeluid.nl/sparql/
#+ idField: suggestion
#+ tags:
#+      - Dive-UI

SELECT ?type ?entity ?label ?description ?startDate ?endDate ?relations
WHERE {
  VALUES (?type ?entity ?label ?description ?startDate ?endDate) {
    ( "person" "person-paul" "Paul McCartney"  "This is Paul" "" "" )
    ( "concept" "concept-rocknroll" "Rock 'n Roll"  "This is rock 'n roll, woohoo!"  "" "" )
    ( "event" "event-beatles-amsterdam" "Beatles in Amsterdam"  "The beatles were in Amsterdam"  "1970-10-06 12:00" "1970-10-06 23:00" )
    ( "mediaobject" "mediaobject-beatles-boat-tour" "Beatles on a boat tour"  "Beatles on a boat tour trough Amsterdam"  "" "" )
    ( "location" "location-amsterdam" "Amsterdam"  "Amsterdam is the Dutch Capital city"  "" "" )
    ( "project" "project-beatles-in-nl" "Beatles in NL"  "A Project about the visit of the beatles in the Netherlands"  "" "" )
  }
  BIND("Popular," as ?relations)
}
