#+ summary: Returns a list of statistics
#+ endpoint: http://data.dive.beeldengeluid.nl/sparql/
#+ idField: type
#+ tags:
#+      - Dive-UI

SELECT ?type ?count ?title ?description WHERE {
  VALUES (?type ?count ?title ?description) {
   ( "event"        8123 "Events"       "An event")
   ( "mediaobject" 23116 "MediaObjects" "MediaObjects description" )
   ( "person"       1222 "People"       "People description" )
   ( "location"     6051 "Locations"    "Locations description" )
   ( "concept"      4988 "Concepts"     "Concepts description" )
   ( "project"       123 "Projects"     "Projects description" )

  }
}
