#+ summary: Returns a list of suggested terms
#+ endpoint: http://data.dive.beeldengeluid.nl/sparql/
#+ idField: suggestion
#+ tags:
#+      - Dive-UI

SELECT ?suggestion WHERE {
  VALUES (?suggestion) {
   ("Wim Kok")
   ("Ruud Lubbers")
   ("Rotterdam")
   ("Vredespaleis")
   ("schaatsen")
   ("zomer")
  }
}
