#+ summary: Returns a list of statistics
#+ endpoint: http://data.dive.beeldengeluid.nl/sparql/
#+ idField: type
#+ tags:
#+      - Dive-UI
SELECT ?type ?count ?label ?description WHERE {
  {
    SELECT ?type (COUNT(?item) as ?count) {
      VALUES ?type {
         <http://semanticweb.cs.vu.nl/2009/11/sem/Event>
         <http://semanticweb.cs.vu.nl/2009/11/sem/Actor>
         <http://semanticweb.cs.vu.nl/2009/11/sem/Place>
         dive:MediaObject
         skos:Concept
      }
      ?item rdf:type ?type
    } GROUP BY ?type
  }
  ?type rdfs:label ?label .
  OPTIONAL { ?type (rdfs:comment|skos:definition) ?description }
}
