#+ summary: List media objects with no source
#+ endpoint: http://data.dive.beeldengeluid.nl/sparql/
#+ headers: { 'Accept' : 'application/sparql-results+json' }
#+ idField: item
#+ tags:
#+      - Dive-Dashboard (unused)

PREFIX am: <http://vocab.deri.ie/am#>
PREFIX edm: <http://www.europeana.eu/schemas/edm/>
PREFIX dive: <http://purl.org/collections/nl/dive/>

SELECT ?item  WHERE {
    ?item dive:inCollection <?_collection> .
    ?item a ?type .
    ?type rdfs:subClassOf* dive:MediaObject .
    ?item am:title ?title .
    OPTIONAL {?item dive:source ?src}
    OPTIONAL {?item edm:object ?src2}
    FILTER (!bound(?src) && !bound(?src2))
}
